version: "3"

services:
  test:
    image: us.gcr.io/custom-plating-209314/hex_raster_processor
    build: .
    command: >
      bash -c "
      python setup.py develop
      && flake8 hex_raster_processor/*.py tests
      && pytest"
    volumes:
      - .:/app/
 