version: 2.0

jobs:
  build-and-test:
    docker:
      - image: python:3.9-buster
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Install packages for python dev and libgnutls28 dev
          command: |
            apt-get update -y 
            apt-get install -y python3-setuptools build-essential libgnutls28-dev python3-pip python-dev python-pil python-gdal libgdal-dev gdal-bin dans-gdal-scripts
      - run:
          name: Creating venv and install packages
          command: |
            python3 -m venv app_env
            . app_env/bin/activate
            pip install --upgrade --no-cache-dir setuptools==57.5.0
            pip install numpy
            pip install gdal==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"
            pip install --no-cache-dir -r requirements_dev.txt
            python setup.py develop
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements_dev.txt" }}
          paths:
            - app_env
      - run:
          name: Running tests for apps
          command: |
            . app_env/bin/activate
            flake8 hex_raster_processor/*.py tests
            pytest -s

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
